version: '3.4'

services:
  db:
    image: mariadb:10.2.25
    restart: always
    environment:
      # Informations à modifier à votre gré
      MYSQL_USER: coud0011
      MYSQL_PASSWORD: 1Mot2Pass
      MYSQL_ROOT_PASSWORD: secretR00tPassw0rd
      MYSQL_DATABASE: dbDockerContacts
  php:
    build:
      context: .
      target: contacts_php
    depends_on:
      - db
    volumes:
      - ./:/srv/contacts
      - ./docker/php/conf.d/config.ini:/usr/local/etc/php/conf.d/dev.ini
  
  web:
    build:
      context: .
      target: contacts_nginx
    depends_on:
      - php
    volumes:
      - ./public:/srv/contacts/public:ro
    ports:
      - target: 80
        published: 8080