version: '3.4'

services:
  db:
    image: mariadb
    restart: always
    environment:
      # Informations à modifier à votre gré
      MYSQL_USER: coud0011
      MYSQL_PASSWORD: 1Mot2Pass
      MYSQL_ROOT_PASSWORD: secretR00tPassw0rd
      MYSQL_DATABASE: dbDockerContacts
  php:
    build:
      context: .
      dockerfile: contacts_php
    depends_on:
      - db
    volumes:
      - .:/srv/contacts
      - docker/php/conf.d/dev.ini:/usr/local/etc/php/config.ini