version: '3.7'
services:
  db:
    image: mariadb:10.2.25
    restart: always
    environment:
      # Informations à modifier à votre gré
      MYSQL_USER: ${MYSQL_USER:?invalidUser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:?invalidPassword}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?invalidRootPassword}
      MYSQL_DATABASE: ${MYSQL_DATABASE:?invalidDatabase}

  php:
    #build:
    #  context: ../
    #  target: contacts_php_prod
    image: ${PHP_IMAGE:?invalidPhpImage}:${APP_VERSION:?invalidAppVersion}
    restart: always
    depends_on:
      - db
    # volumes:
    #   - ./:/srv/contacts
    #   - ./docker/php/conf.d/config.ini:/usr/local/etc/php/conf.d/dev.ini
  
  web:
    build:
      context: ../.
      target: contacts_nginx_prod
    depends_on:
      - php
    volumes:
      - ./public:/srv/contacts/public/:ro
    ports:
      - target: 80
        published: 8000
###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
